# Generated by Django 4.0.1 on 2022-02-12 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_about_you_customuser_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='About_you',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Your_socials',
            new_name='socials',
        ),
    ]
